# Generated by Django 3.1.7 on 2021-03-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_remove_goods_goods_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
