# Generated by Django 3.1.7 on 2021-03-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_goods_goods_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='goods_id',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
