# Generated by Django 3.1.7 on 2021-03-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_auto_20210302_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_total',
            field=models.IntegerField(null=True),
        ),
    ]
