# Generated by Django 3.1.7 on 2021-03-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_goods_goods_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goods_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goods_id',
            new_name='id_str',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goods_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goods_price',
            new_name='price',
        ),
    ]
