# Generated by Django 3.1.7 on 2021-03-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_auto_20210302_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
