# Generated by Django 3.1.7 on 2021-03-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_goods_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
