# Generated by Django 3.1.7 on 2021-03-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_auto_20210304_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
