# Generated by Django 3.1.7 on 2021-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_delete_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
