# Generated by Django 3.1.7 on 2021-03-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0013_auto_20210304_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Furniture', 'Furniture')], max_length=200, null=True),
        ),
    ]
